### ISSUE TITLE
Forms issues 2

### ISSUE THREAD

**Issue by fredrikjva** [RosanderOliver/DV1512_Projekt_HT2015#44]
test_num($data) returns "-" ONLY if the input data is "-" and not any other value that are ether greater than 6 or smaller than 0

input_length() returns the whole string even if it's longer than 128 bytes.
length_one() has the same problem and probably length_three() as well.

**Comment by RosanderOliver** [comment]
Fixed and push to examinator_grading.

**Comment by fredrikjva** [comment]
It works now!
